project:
  render: 
    - presentation.qmd

date: today
format: 
  revealjs:
    logo: images/image3.png
    theme: presentation-theme-bc3.scss
    monofont: "Cascadia Code"
    slide-number: true
    auto-stretch: false
    css: style.css
number-sections: true
code-line-numbers: false
code-copy: true
toc: false
# toc-depth: 1
code-overflow: wrap
slide-level: 3

execute: 
  eval: false
  echo: true